version: '3.1'
services:
  #servidor banco de dados
  db:
    image: mysql
    environment:
      #Senha do user 'root'
      MYSQL_ROOT_PASSWORD: example
      #Nome da base de dados
      MYSQL_DATABASE: db  
      #Usuario da base
      MYSQL_USER: leo
      #Senha da base
      MYSQL_PASSWORD: leo
    ports:
      - 3306:3306  
  # gerenciador de base de dados
  adminer:
    image: adminer
    ports:
      - 8081:8080
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80