-- CRIAR A TABELA PLACA PRIMEIRO --
CREATE TABLE Carro (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ano INT,
    modelo VARCHAR(50),
    montadora VARCHAR(50),
    placa_id INT,
    CONSTRAINT fk_carro_placa FOREIGN KEY (placa_id) REFERENCES Placa(id) ON DELETE SET NULL ON UPDATE SET NULL
    );



